name: Develop Branch CI/CD
 
on:
 push:
   branches: [ develop ]
 pull_request:
   branches: [ develop ]
 
 
jobs:
 build-test:
   runs-on: ubuntu-latest
   strategy:
     matrix:
       node-version: [17.x]
   steps:
   - uses: actions/checkout@v2
   - name: Use Node.js ${{ matrix.node-version }}
     uses: actions/setup-node@v1
     with:
       node-version: ${{ matrix.node-version }}
   - run: npm install
   - name: Cypress run
     uses: cypress-io/github-action@v2
     with:
        build: npm run build
        start: npm run dev
        wait-on: 'http://localhost:3000'
 build-s3:
   needs: build-test
   runs-on: ubuntu-latest
   strategy:
     matrix:
       node-version: [17.x]
   steps:
   - uses: actions/checkout@v2
   - name: Use Node.js ${{ matrix.node-version }}
     uses: actions/setup-node@v1
     with:
       node-version: ${{ matrix.node-version }}
   - run: npm install
   - run: npm run build
   - name: Set AWS credentials
     uses: aws-actions/configure-aws-credentials@v1
     with:
       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       aws-region: us-west-1
   - run: curl https://gist.githubusercontent.com/nielsdejong/5be9e87e71aa06be5695a57a0daec04c/raw/f3673787d74d402b4450a4a58025e64feb4466d5/index.html > dist/index.html
   - run: aws s3 rm s3://neodash-test.graphapp.io/ --recursive && aws s3 sync dist s3://neodash-test.graphapp.io/ --acl public-read